# Generated by Django 2.2.1 on 2019-05-30 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibUser',
            fields=[
                ('libId', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='lib id')),
                ('libPsw', models.CharField(max_length=30, verbose_name='lib password')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('openId', models.CharField(max_length=100, null=True, verbose_name='open id')),
                ('wxSessionKey', models.CharField(max_length=100, null=True, verbose_name='wx session key')),
                ('session', models.CharField(max_length=100, null=True, verbose_name='session')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('nickName', models.CharField(max_length=100, null=True, verbose_name='nick name')),
                ('avatarUrl', models.CharField(max_length=200, null=True, verbose_name='avatar url')),
                ('gender', models.IntegerField(null=True, verbose_name='gender')),
                ('province', models.CharField(max_length=100, null=True, verbose_name='province')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='city')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='country')),
                ('lastLoginTime', models.DateTimeField(null=True, verbose_name='last login time')),
                ('libAccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lib', to='mplib.LibUser', verbose_name='lib account')),
            ],
        ),
    ]
